# Generated by Django 5.2.6 on 2025-09-19 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_studentmodel_user'),
        ('teachers', '0002_alter_teachermodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lesson_type', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical'), ('Lecture', 'Lecture'), ('laboratory', 'Laboratory'), ('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Exam', 'Exam'), ('Review', 'Review')], default='Theory')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('prerequisites', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_free', models.BooleanField(default=True)),
                ('rate', models.IntegerField(default=0)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('score', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['price', 'rate'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='teachers.teachermodel')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.course')),
            ],
            options={
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('grade', models.CharField(max_length=50)),
                ('prerequisites', models.CharField(blank=True, max_length=50)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('semester', models.CharField()),
                ('schedule', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=45)),
                ('lesson_type', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical'), ('Lecture', 'Lecture'), ('laboratory', 'Laboratory'), ('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Exam', 'Exam'), ('Review', 'Review')], default='Theory')),
                ('material', models.TextField(blank=True, help_text='Links for all about things you need')),
                ('score', models.CharField(max_length=5)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='classes.class')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateField(auto_now_add=True)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.studentmodel')),
            ],
            options={
                'unique_together': {('student', 'class_instance')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused')], default='Absent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='students.studentmodel')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_attendance', to='classes.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attendance', to='classes.lesson')),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
