# Generated by Django 5.2.6 on 2025-09-11 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('education_level', models.CharField(choices=[('Bachelor', "Bachelor's Degree"), ('Master', "Master's Degree"), ('PhD', "PhD's Degree"), ('Postdoctoral', "Postdoctoral's Degree")], default='Bachelor')),
                ('hire_date', models.DateTimeField()),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('subjects', models.ManyToManyField(related_name='Teachers_Subject', to='teachers.subjects')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
